version: '3.7'

services:
    web:
        container_name: CyberGuard_App
        build: .
        restart: always
        env_file:
            - .env
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        depends_on:
            - db
        links:
            - db
        ports:
            - ${APP_PORT}:${APP_PORT}
        command: npm run dev

    db:
       image: postgres
       env_file:
         - .env 
       restart: always
       ports:
         - '5432:5432'
       environment:
         POSTGRES_USER: ${POSTGRES_USER}
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
         POSTGRES_DB: ${POSTGRES_DB}
volumes:
    dbdata-volume: